      - name: Commit updated vacancies
        run: |
          git config --global user.user "LokIT Bot 🤖"
          git config --global user.email "lokit-bot@users.noreply.github.com"

          git status

          git add public/vacancies.json

          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "🔄 Update IT vacancies — $(date +'%Y-%m-%d')"

          git push origin HEAD:main
